site_name: MkDocs French Plugin
site_url: https://yves-chevallier.github.io/mkdocs-french/
site_author: Yves Chevallier
repo_name: yves-chevallier/mkdocs-french
repo_url: https://github.com/yves-chevallier/mkdocs-french
copyright: Copyright &copy; 2025 Yves Chevallier
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode clair
  icon:
    repo: fontawesome/brands/github
nav:
  - Introduction: index.md
  - Configuration: config.md
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yves-chevallier/mkdocs-french
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html
extra_css:
  - css/pied-piper.css
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            line_length: 88
            show_signature: true
            show_source: true
  - french:
      ligatures: fix
      summary: true
      units: fix
      ordinaux: fix
      diacritics: fix
      admonition_translations:
        pied-piper: "Joueur de flûte"
