site_name: MkDocs French Plugin
site_url: https://yves-chevallier.github.io/mkdocs-french/
site_author: Yves Chevallier
repo_name: yves-chevallier/mkdocs-french
repo_url: https://github.com/yves-chevallier/mkdocs-french
copyright: Copyright &copy; 2025 Yves Chevallier
theme:
  language: fr
  name: material
  logo: https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg
  font:
    text: Open Sans
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Basculer en mode sombre
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode clair
  icon:
    repo: fontawesome/brands/github
nav:
  - Introduction: index.md
  - Configuration: config.md
  - Référence:
      - Package mkdocs_french: reference/index.md
      - Dictionnaire: reference/dictionary.md
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yves-chevallier/mkdocs-french
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html
  - toc:
      permalink: true
  - def_list
  - footnotes
  - attr_list
  - md_in_html
extra_css:
  - css/pied-piper.css
extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_docstring_description: true
            show_signature_annotations: true
            docstring_style: google
            separate_signature: true
            merge_init_into_class: true
  - pills
  - french:
      ligatures: fix
      summary: true
      units: fix
      ordinaux: fix
      diacritics: fix
      admonition_translations:
        pied-piper: "Joueur de flûte"
